f = open('srucode.txt','w')
for i in range(1,17):
	print >> f,"st"+str(i)+":" 
	print >> f,"begin"
	print >> f,"efifo_rd_en <= 1'b0;"
	print >> f,"sru_payload_cnt_ctrl <= spc_ctrl0;"
	print >> f,"ddl_payload_cnt_ctrl <= 1'b0;"
	print >> f,"efifo_st_ctrl <= es_ctrl0;"
	print >> f,"ch_cnt_ctrl <= cc_ctrl0;"
	print >> f,"ebfifo_wr_sel <= ebfifo_wr_s0; //cdh0"+str((i-1)/2)+";"
	print >> f,"st <= st"+str(i+1)+";"
	print >> f,"end"
	print >> f,""
	
f = open('srucode.txt','w')
for i in range(0,18):
	print >> f,"st_tra_"+str(i)+":" 
	print >> f,"begin"
	print >> f,"efifo_rd_en <= 1'b0;"
	print >> f,"sru_payload_cnt_ctrl <= spc_ctrli;//no change"
	print >> f,"ddl_payload_cnt_ctrl <= 1'b0;//no change"
	print >> f,"efifo_st_ctrl <= es_ctrl0;"
	print >> f,"ch_cnt_ctrl <= cc_ctrl0;"
	print >> f,"ebfifo_wr_sel <= ebfifo_wr_s"+str(i+18)+";//trailer"+str((i)/2)+";"
	print >> f,"st <= st_tra_"+str(i+1)+";"
	print >> f,"end"
	print >> f,""	

f = open('srucode.txt','w')
print >> f,"parameter ebfifo_wr_s"+str(i)+" = 36'h"+str(hex(k<<i))+";"

for i in range(20,40):
		print >> f,"dtc_master_top u_dtc_master_top"+str(i)+"("
		print >> f,"//dtc phy"
		print >> f,".dtc_clk_p(dtc_clk_p["+str(i)+"])," 
		print >> f,".dtc_clk_n(dtc_clk_n["+str(i)+"]),"
		print >> f,""
		print >> f,".dtc_trig_p(dtc_trig_p["+str(i)+"])," 
		print >> f,".dtc_trig_n(dtc_trig_n["+str(i)+"]),"
		print >> f,""
		print >> f,".dtc_data_p(dtc_data_p["+str(i)+"])," 
		print >> f,".dtc_data_n(dtc_data_n["+str(i)+"]),"
		print >> f,""
		print >> f,".dtc_return_p(dtc_return_p["+str(i)+"]),"
		print >> f,".dtc_return_n(dtc_return_n["+str(i)+"]),"
		print >> f,""
		print >> f," //fee status flag"
		print >> f,".fee_flag(fee_flag["+str(i)+"])," 		
		print >> f,""
		print >> f,"//trigger pulse input"
		print >> f,".trig_in(trig_in|dtc_altrofreecmd),"
		print >> f,".sru_l0(sru_l0), 	"
		print >> f,".sru_l1(sru_l1), 	"
		print >> f,".sru_l2r(sru_l2r), 	"
		print >> f,".ebstart(ebstart), "
		print >> f,".dtc_window_mode(dtc_window_mode), "
		print >> f,""
		print >> f,".dtc_efifoflag(dtc_efifoflag_i["+str(i)+"]), "	
		print >> f,".dtc_busyflag(dtc_busyflag_i["+str(i)+"]), 	"
		print >> f,".dtc_altrofreeflag(dtc_altrofreeflag_i["+str(i)+"]), "	
		print >> f,""
		print >> f," //command reply	"	
		print >> f,".gclk_40m(gclk_40m),"
		print >> f,".gclk_40m_n(gclk_40m_n),"
		print >> f,".dcs_rx_clk(dcs_rx_clk), "
		print >> f,".dcs_rxd(dcs_rxd), "
		print >> f,".dcs_rx_dv(dcs_rx_dv["+str(i)+"]),"		
		print >> f,""
		print >> f,".reply_send_cmd(reply_send_cmd["+str(i)+"]),"
		print >> f,".udp_tx_fifo_din(udp_tx_fifo_din),"
		print >> f,".udp_tx_fifo_wr_en(udp_tx_fifo_wr_en_i["+str(i)+"]),"
		print >> f,".udp_tx_req(udp_tx_req_i["+str(i)+"]),"		
		print >> f,""
		print >> f," //event data receive interface	"	
		print >> f,".efifo_rd_clk(efifo_rd_clk), "
		print >> f,".efifo_rd_en(efifo_rd_en["+str(i)+"]), "
		print >> f,".efifo_dout(efifo_dout1),"
		print >> f,".efifo_empty(efifo_empty["+str(i)+"]),"
		print >> f,".efifo_cs(efifo_cs["+str(i)+"]),"
		print >> f,""
		print >> f,"//clock interface"
		print >> f,".dout_p_detect(dout_p_detect["+str(i)+"]),	"	
		print >> f,".dtc_clk_ps(dtc_clk_ps["+str(i)+"]),"
		print >> f,".dtc_clkin(dtc_clk_fix["+str(i)+"]),"
		print >> f,""
		print >> f,".dtc_rdo_en(dtc_rdo_en["+str(i)+"]),"
		print >> f,".dtc_ecnt(dtc_ecnt"+str(i)+"),"
		print >> f,""
		print >> f,".reset(reset));"
		print >> f,""
		print >> f,"//********************************************************"
		print >> f,""



